services:
  trmd:
    image: gentlesprite/telegram_restricted_media_downloader:latest
    container_name: trmd
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./config:/app/TRMD
      - ./sessions:/app/sessions
      - ./downloads:/app/downloads
      - ./temp:/app/temp
      - ./form:/app/form
    environment:
      - TZ=Asia/Shanghai